---
- name: encode demo
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: encode between JSON and YAML
      vars:
        hosts:
          - name: bastion
            ip:
              - 172.25.250.254
              - 172.25.252.1
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "{{ hosts | to_json }}"
        - "{{ hosts | to_nice_json }}"
