---
- name: convert demo
  hosts: localhost
  gather_facts: false
  vars:
    hosts:
      - name: bastion
        ip:
          - 172.25.250.254
          - 172.25.252.1  
  tasks:
    - name: converting between dictionaries and lists
      ansible.builtin.debug:
        msg: "'{{ hosts | to_nice_json }}'"
