---
- name: Both tasks have the same result
  hosts: servera.lab.example.com
  gather_facts: false
  tasks:

    - name: Iteration Option One
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ query('fileglob', lookup('env', 'HOME') + '/.bash*') }}"

    - name: Iteration Option Two
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_fileglob: "{{ lookup('env', 'HOME') + '/.bash*' }}"

- name: Show results of fileglob
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show matching files
      debug:
        var: lookup('ansible.builtin.fileglob', lookup('env', 'HOME') + '/.bash*', wantlist=True)

