---
- name: demo lookup query
  hosts: localhost
  gather_facts: false
  vars:
    output: "{{ query('ansible.builtin.lines', 'ls files') }}"
  
  tasks:
    - name: Shows the lookup
      ansible.builtin.debug:
        msg: "{{ output }}"
